### PR TITLE
changed lineWidth of indicator series

### PR DESCRIPTION
**Pull request by adamlawrencium**

### CODE REVIEW

**Comment by aeksco** [comment]
:+1: Really changing the game with this one

**Comment by BirchellE** [comment]
I think this change represents a real negative change in the codebase. I'm actually insulted you would dare make this change without consulting me first.

**Comment by BirchellE** [comment]
jk

**Comment by adamlawrencium** [comment]
Here's to the crazy ones, the misfits, the rebels, the troublemakers, the lineWidth:1.25 series in a lineWidth:2.0 world... the ones who see things differently -- they're not fond of rules... You can quote them, disagree with them, glorify or vilify them, but the only thing you can't do is ignore them because they change things... they push the human race forward, and while some may see them as the crazy ones, we see genius, because the ones who are crazy enough to think that they can change the world, are the ones who do.

**Pull request merged**
